mkdir testSource

#    testSource/
#    ├── test_dir1
#    │   ├── test_dir1.txt
#    │   ├── test_dir1_1
#    │   │   └── test_dir1_1.txt
#    │   └── test_dir1_2
#    │       └── test_dir1_2.txt
#    ├── test_dir2
#    │   ├── test_dir2.txt
#    │   ├── test_dir2_1
#    │   │   └── test_dir2_1.txt
#    │   └── test_dir2_2
#    │       └── test_dir2_2.txt
#    └── test_dir3
#        ├── test_dir3.txt
#        ├── test_dir3_1
#        │   └── test_dir3_1.txt
#        └── test_dir3_2
#            └── test_dir3_2.txt


mkdir testSource/test_dir1
echo "test_dir1" > testSource/test_dir1/test_dir1.txt
mkdir testSource/test_dir2
echo "test_dir2" > testSource/test_dir2/test_dir2.txt
mkdir testSource/test_dir3
echo "test_dir3" > testSource/test_dir3/test_dir3.txt

mkdir testSource/test_dir1/test_dir1_1
echo "test_dir1_1" > testSource/test_dir1/test_dir1_1/test_dir1_1.txt

mkdir testSource/test_dir1/test_dir1_2
echo "test_dir1_2" > testSource/test_dir1/test_dir1_2/test_dir1_2.txt

mkdir testSource/test_dir2/test_dir2_1
echo "test_dir2_1" > testSource/test_dir2/test_dir2_1/test_dir2_1.txt

mkdir testSource/test_dir2/test_dir2_2
echo "test_dir2_2" > testSource/test_dir2/test_dir2_2/test_dir2_2.txt

mkdir testSource/test_dir3/test_dir3_1
echo "test_dir3_1" > testSource/test_dir3/test_dir3_1/test_dir3_1.txt

mkdir testSource/test_dir3/test_dir3_2
echo "test_dir3_2" > testSource/test_dir3/test_dir3_2/test_dir3_2.txt

# create the test FS binary image
littlefs_create -i testSource.bin -s testSource

# List files in the generated binary and compare to the expected output
outputSum=$( littlefs_list -i testSource.bin | md5sum )
expectedSum="ba9751373f9cfb2a3502e99d8359fe1a  -" # generated by running littlefs_list -i testSource.bin  | md5sum 

if [ "$outputSum" != "$expectedSum" ]; then
    echo "Test failed"
    echo "Expected: $expectedSum"
    echo "Got:      $outputSum"
    exit 1
else
    echo "List comparison Test passed"
fi

# extract the test FS binary image contents to a new directory
littlefs_extract -i testSource.bin -d testSourceExtracted

#diff contents of the extracted directory to the original directory. pass if they are the same
diff -r testSource testSourceExtracted
if [ $? -ne 0 ]; then
    echo "Extract comparison Test failed"
    exit 1
else
    echo "Extract comparison Test passed"
fi