mkdir testSource

# testSource.bin
#   test_dir1
#       *---test_dir1.txt (10.0 B)
#       test_dir1_1
#           *---test_dir1_1.txt (12.0 B)
#       test_dir1_2
#           *---test_dir1_2.txt (12.0 B)
#   test_dir2
#       *---test_dir2.txt (10.0 B)
#       test_dir2_1
#           *---test_dir2_1.txt (12.0 B)
#       test_dir2_2
#           *---test_dir2_2.txt (12.0 B)
#   test_dir3
#       *---test_dir3.txt (10.0 B)
#       test_dir3_1
#           *---test_dir3_1.txt (12.0 B)
#       test_dir3_2
#           *---test_dir3_2.txt (12.0 B)


mkdir testSource/test_dir1
echo "test_dir1" > testSource/test_dir1/test_dir1.txt
mkdir testSource/test_dir2
echo "test_dir2" > testSource/test_dir2/test_dir2.txt
mkdir testSource/test_dir3
echo "test_dir3" > testSource/test_dir3/test_dir3.txt

mkdir testSource/test_dir1/test_dir1_1
echo "test_dir1_1" > testSource/test_dir1/test_dir1_1/test_dir1_1.txt

mkdir testSource/test_dir1/test_dir1_2
echo "test_dir1_2" > testSource/test_dir1/test_dir1_2/test_dir1_2.txt

mkdir testSource/test_dir2/test_dir2_1
echo "test_dir2_1" > testSource/test_dir2/test_dir2_1/test_dir2_1.txt

mkdir testSource/test_dir2/test_dir2_2
echo "test_dir2_2" > testSource/test_dir2/test_dir2_2/test_dir2_2.txt

mkdir testSource/test_dir3/test_dir3_1
echo "test_dir3_1" > testSource/test_dir3/test_dir3_1/test_dir3_1.txt

mkdir testSource/test_dir3/test_dir3_2
echo "test_dir3_2" > testSource/test_dir3/test_dir3_2/test_dir3_2.txt

# create the test FS binary image
littlefs_create -i testSource.bin -s testSource

# List files in the generated binary and compare to the expected output
outputSum=$( littlefs_list -i testSource.bin | sha256sum )
expectedSum="65a16cd7ad73a9efac9daf12c187bb1969db527203a684b6ec6c5e83ac913abf  -" # generated by running littlefs_list -i testSource.bin  | sha256sum 

if [ "$outputSum" != "$expectedSum" ]; then
    echo "Test failed"
    echo "Expected: $expectedSum"
    echo "Got:      $outputSum"
    exit 1
else
    echo "List comparison Test passed"
fi

# extract the test FS binary image contents to a new directory
littlefs_extract -i testSource.bin -d testSourceExtracted

#diff contents of the extracted directory to the original directory. pass if they are the same
diff -r testSource testSourceExtracted
if [ $? -ne 0 ]; then
    echo "Extract comparison Test failed"
    exit 1
else
    echo "Extract comparison Test passed"
fi