# testSource.bin
#   test_dir1
#       *---test_dir1.txt (10.0 B)
#       test_dir1_1
#           *---test_dir1_1.txt (12.0 B)
#       test_dir1_2
#           *---test_dir1_2.txt (12.0 B)
#   test_dir2
#       *---test_dir2.txt (10.0 B)
#       test_dir2_1
#           *---test_dir2_1.txt (12.0 B)
#       test_dir2_2
#           *---test_dir2_2.txt (12.0 B)
#   test_dir3
#       *---test_dir3.txt (10.0 B)
#       test_dir3_1
#           *---test_dir3_1.txt (12.0 B)
#       test_dir3_2
#           *---test_dir3_2.txt (12.0 B)

testSource="testSource_large"
rm -rf $testSource
mkdir $testSource
mkdir $testSource/test_dir1
echo "test_dir1" > $testSource/test_dir1/test_dir1.txt
mkdir $testSource/test_dir2
echo "test_dir2" > $testSource/test_dir2/test_dir2.txt
mkdir $testSource/test_dir3
echo "test_dir3" > $testSource/test_dir3/test_dir3.txt

mkdir $testSource/test_dir1/test_dir1_1
echo "test_dir1_1" > $testSource/test_dir1/test_dir1_1/test_dir1_1.txt

mkdir $testSource/test_dir1/test_dir1_2
echo "test_dir1_2" > $testSource/test_dir1/test_dir1_2/test_dir1_2.txt

mkdir $testSource/test_dir2/test_dir2_1
echo "test_dir2_1" > $testSource/test_dir2/test_dir2_1/test_dir2_1.txt

mkdir $testSource/test_dir2/test_dir2_2
echo "test_dir2_2" > $testSource/test_dir2/test_dir2_2/test_dir2_2.txt

mkdir $testSource/test_dir3/test_dir3_1
echo "test_dir3_1" > $testSource/test_dir3/test_dir3_1/test_dir3_1.txt

mkdir $testSource/test_dir3/test_dir3_2
echo "test_dir3_2" > $testSource/test_dir3/test_dir3_2/test_dir3_2.txt
# create a 1MiB file in the nested directory
dd if=/dev/zero of=$testSource/test_dir3/test_dir3_2/test_dir3_2-large.txt count=1024 bs=1024

# create the test FS binary image
littlefs_create -i testSource-large.bin -s $testSource -c 300
# check exit code and exit if not successful
if [ $? -ne 0 ]; then
    echo -e "\e[31mlittlefs_create failed\e[0m" 
    exit 1
else
    echo -e "\e[32mlittlefs_create successful\e[0m" 
fi

# List files in the generated binary and compare to the expected output
outputSum=$( littlefs_list -i testSource-large.bin -c 300 | sha256sum )
expectedSum="801b53e121b9c7b382a575d990db3f75711a3d8f859ade2f8c01d61ebecce75a  -" # generated by running littlefs_list -i testSource.bin  | sha256sum 

if [ "$outputSum" != "$expectedSum" ]; then
    echo -e "\e[31mlittlefs_list failed\e[0m" 
    echo "Expected: $expectedSum"
    echo "Got:      $outputSum"
    exit 1
else
    echo -e "\e[32mlittlefs_list passed\e[0m"
fi

# extract the test FS binary image contents to a new directory
rm -rf testSourceExtracted-large
littlefs_extract -i testSource-large.bin -d testSourceExtracted-large -c 300

#check exit code and exit if not 0
if [ $? -ne 0 ]; then
    echo -e "\e[31mlittlefs_extract failed\e[0m" 
    exit 1
fi

#diff contents of the extracted directory to the original directory. pass if they are the same
diff -r $testSource testSourceExtracted-large
if [ $? -ne 0 ]; then
    echo -e "\e[31mExtract comparison Test failed\e[0m" 
    exit 1
else
    echo -e "\e[32mExtract comparison Test passed\e[0m"
fi
