name: Publish package to pypi on tag

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build_wheel:
    name: Build wheel and publish to pypi
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/littlefs-tools
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install build tools
        run: pip install build
      - name: Build package
        run: python -m build
      - name: Publish Package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: false
